services:
  - type: web
    name: Plotly Dash
    env: python
    build:
      context: .
      docker:
        - .
    run:
      command: gunicorn final_dashboard:server
    ports:
      - 10000:10000